name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Thay đổi branch tương ứng với main branch của repository

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies (if any)
        run: |
          # Command to install any dependencies needed
          
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo apt update
            sudo apt install -y nginx
            # Copy your nginx configuration, WordPress files, etc.
            # Restart nginx or services as needed
