name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Ping remote server
        run: |
            ping -c 4 ${{ secrets.SERVER_SSH_PORT }}

      - name: Install SSH client
        run:  sudo apt-get install -y openssh-client

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 127.17.0.1
          username: hien
          password: 352636
          port: 22
          script: |
            cd /var/www/html/wordpress
            git pull origin main
            sudo systemctl restart nginx
            sudo systemctl restart php8.3-fpm
            ./deploy.sh

