name: CI/CD Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y nginx php-cgi sshpass


      - name: Configure and Start PHP-CGI
        run: |
          php-cgi -b 127.0.0.1:9000 &

      - name: Configure and Start Nginx
        run: |
          sudo cp ./nginx/nginx.conf /etc/nginx/nginx.conf
          sudo systemctl restart nginx



      - name: Test WordPress Admin Login
        run: |
          curl -s http://localhost/wp-admin | grep "WordPress"
