name: Deploy to Server

on:
  push:
    branches:
      - main  # Thay đổi trên nhánh main sẽ kích hoạt workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Cài đặt SSH client để kết nối tới máy chủ
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client
      
      # Sử dụng webfactory/ssh-agent để sử dụng SSH key từ secrets
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      # Ping máy chủ để kiểm tra kết nối
      - name: Ping remote server
        run: ping -c 4 ${{ secrets.SERVER_SSH_HOST}}

      # Kiểm tra kết nối SSH tới máy chủ
      - name: Check SSH connectivity
        run: nc -zv ${{ secrets.SERVER_SSH_HOST }} 22
      
      # Triển khai ứng dụng bằng lệnh SSH
      # Deploy application using SSH
      - name: Deploy application
        run: |
          ssh -o StrictHostKeyChecking=no 
              "${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_SSH_HOST }}" << 'EOF'
            cd /var/www/html  # Đường dẫn tới WordPress trên máy chủ
            git pull origin main  # Lấy mã nguồn mới nhất từ repository
            sudo systemctl restart nginx  # Khởi động lại NGINX để áp dụng thay đổi
            sudo systemctl restart php8.3-fpm  # Khởi động lại PHP-FPM
          EOF


      # Kiểm tra kết quả triển khai
      - name: Check deployment result
        run: |
          curl -sI http://${{ secrets.SERVER_HOST }}  # Kiểm tra trang chủ đã hoạt động
          curl -sI http://${{ secrets.SERVER_HOST }}/wp-admin  # Kiểm tra trang quản trị WordPress
