name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Check key
        uses: webfactory/ssh-agent@v0.5.3
        with:
            ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
      
      - name: Ping remote server
        run: |
            ping -c 4 ${{ secrets.SERVER_IP }}
      - name: Check SSH
        run: |
            nc -zv ${{ secrets.SERVER_IP}} 22

      - name: Check SSH Username
        run: |
            echo "Current user $(whoami)"
            echo "User enviroment variable: ${{ secrets.SERVER_USERNAME}}"

      
      - name: Test SSH connection
        run: |
             ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME}}@$${{ secrets.SERVER_IP}} 'echo "SSH"'
             
      - name: Install SSH client
        run:  sudo apt-get install -y openssh-client

    

