name: Deploy to Server

on:
  push:
    branches:
      - main  # Trigger khi có thay đổi trên nhánh main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Cài đặt SSH client để kết nối tới máy chủ
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client
      
      # Sử dụng webfactory/ssh-agent để sử dụng SSH key từ secrets
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
      
      # Ping máy chủ để kiểm tra kết nối
      - name: Ping remote server
        run: ping -c 4 ${{ secrets.SERVER_HOST }}

      - name: Pull latest code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd /path/to/your/repo || exit
            git status
            git pull origin main || { echo 'Git pull failed'; exit 1; }
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          
      - name: Deploy via SSH - Restart PHP
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            echo "Restarting php8.3-fpm"
            sudo systemctl restart php8.3-fpm

      - name: Deploy via SSH - Update packages
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            echo "Updating packages"
            sudo apt update

      - name: Deploy via SSH - Install Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            echo "Installing nginx"
            sudo apt install -y nginx

      - name: Deploy via SSH - Run deploy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            echo "Running deploy script"
            ./deploy.sh
            
      - name: Deploy via SSH - Pull latest code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            echo "Pulling latest code from git"
            git pull origin main
      
      # Kiểm tra kết quả triển khai
      - name: Check deployment result
        run: |
          curl -sI http://${{ secrets.SERVER_SSH_HOST }}
          curl -sI http://${{ secrets.SERVER_SSH_HOST }}/wp-admin
