name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies (if any)
        run: |
          # Command to install any dependencies needed

      - name: Setup SSH KEY
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_PUBKEY }}" > ~/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Ubuntu via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo apt update
            sudo apt install -y nginx
            # Copy your nginx configuration, WordPress files, etc.
            # Restart nginx or services as needed
